#pragma once
 #define EE_HANDS
 #define USE_SERIAL
 #define SOFT_SERIAL_PIN D3
 #define FORCED_SYNC_THROTTLE_MS 100
 #define SPLIT_CONNECTION_CHECK_TIMEOUT 500
 #define SPLIT_TRANSPORT_MIRROR
 #define SPLIT_MODS_ENABLE
 #define SERIAL_DEBUG
 #define SELECT_SOFT_SERIAL_SPEED 1
 #define SPLIT_USB_DETECT
 #define SPLIT_USB_TIMEOUT 2500
 #define SPLIT_OLED_ENABLE
 #define SPLIT_LAYER_STATE_ENABLE
 #define SPLIT_LED_STATE_ENABLE
 #define SPLIT_ACTIVITY_ENABLE
