#pragma once
#define EE_HANDS
#define USE_SERIAL
#define SOFT_SERIAL_PIN D0
#define FORCED_SYNC_THROTTLE_MS 100
#define SPLIT_CONNECTION_CHECK_TIMEOUT 500
#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_MODS_ENABLE
#define SERIAL_DEBUG
#define SELECT_SOFT_SERIAL_SPEED 1
#define SPLIT_USB_DETECT
#define SPLIT_USB_TIMEOUT 2500
#define BOOTMAGIC_ROW 0
#define BOOTMAGIC_COLUMN 0
