#pragma once
#define EE_HANDS
#define USE_SERIAL
#define SOFT_SERIAL_PIN D1
#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_MODS_ENABLE
#define SPLIT_USB_DETECT
#define SPLIT_USB_TIMEOUT 2500
#define SPLIT_OLED_ENABLE
#define SPLIT_ACTIVITY_ENABLE
